name: Build Vue
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: install node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run:  export BACKEND_SERVER='https://resume-backend-bikash.herokuapp.com/' && npm run build
      - name: push to bikashnpanda.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'bikashnpanda'
          destination-repository-name: 'bikashnpanda.github.io'
          user-email: oksbwn@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
